-- 0001_extensions_and_conventions.sql
--
-- Baseline migration. Installs the extensions the schema depends on and records
-- the conventions every later migration must follow. No business tables are
-- created here.
--
-- CONVENTIONS (enforced by review; several are also enforced by CI):
--
--   * Primary keys are `uuid`, holding a UUIDv7 generated in application code.
--     Ids are never generated by the database, so that the offline milestone can
--     move generation to the browser without a schema change.
--
--   * All timestamps are `timestamptz`. Storage is UTC; display is shop time
--     (America/Port-au-Prince) for every user, everywhere.
--
--   * Quantities are `integer`, in whole base units. Never `real`, `double
--     precision`, or `numeric`. A floating-point quantity in an inventory ledger
--     is an unfixable defect once history exists. CI rejects `real` and `double
--     precision` in any migration.
--
--   * Money is `bigint`, in minor units (centimes), with an explicit currency
--     column. Never a float.
--
--   * Enumerations are `text` with a CHECK constraint, never native ENUM types.
--     Adding a value is comparable either way; renaming or removing one from a
--     native enum is painful.
--
--   * Booleans are `boolean NOT NULL DEFAULT`, never nullable three-state flags.
--
--   * Rows that participate in inventory history are deactivated, never deleted.
--     Foreign keys onto them use ON DELETE RESTRICT.
--
--   * `inventory_movements`, when it arrives, is append-only: BEFORE UPDATE and
--     BEFORE DELETE triggers raise, and the application role is granted only
--     SELECT and INSERT on it.

BEGIN;

-- Case-insensitive text, for usernames. Employees will type their name at a
-- shop counter; case must not be a login failure.
CREATE EXTENSION IF NOT EXISTS citext;

-- Cryptographic primitives, used for digest() when hashing request bodies for
-- idempotency checks.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

COMMIT;
