import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { CatalogMetadataResponse, Product } from '@ekon/shared';
import { useAuth } from '../../auth/useAuth.js';
import { ErrorNotice } from '../../components/ErrorNotice.js';
import {
  FIELD_ERROR,
  FIELD_HINT,
  FIELD_LABEL,
  OUTCOME_FOCUS,
  PANEL,
  PRIMARY_BUTTON,
  PRIMARY_BUTTON_BUSY,
  SECONDARY_BUTTON,
  TEXT_INPUT,
} from '../../components/styles.js';
import { useTranslator } from '../../i18n/index.js';
import { ApiError, NetworkError } from '../../lib/api.js';
import { createProduct } from '../../lib/catalogApi.js';
import { catalogMetadataQueryKey } from '../../lib/metadataQueries.js';
import { catalogProductsQueryKey } from '../../lib/catalogQueries.js';
import {
  emptyNewProduct,
  emptyVariant,
  toCreateProductRequest,
  validateNewProductForm,
  type NewProductFieldErrors,
  type NewProductFormValues,
} from '../../lib/merchandise.js';
import { VariantFields } from './VariantFields.js';

/**
 * Entering merchandise: a brand, a name, how it is classified, and the sellable
 * identities under it.
 *
 * The model behind this is rich — classification, controlled attributes, price,
 * cost, barcodes — and the whole design problem is keeping the form from
 * feeling like it. Two things do most of that work:
 *
 *  - **two sections and no more**, one for the product and one for its options,
 *    so nobody has to hold a hierarchy in their head to fill it in;
 *  - **everything optional stays optional and looks it**. A shop can enter a
 *    name and one variant and stop, which is exactly what a fresh installation
 *    does on its first day.
 *
 * **The vocabulary comes from the server.** Attribute names are structure — the
 * catalog refuses one it has never heard of — so they are a list to choose from
 * rather than a box to type in. That is a usability decision and a correctness
 * one: a free-text name is a rejection waiting to happen, and the person typing
 * it has no way to know which names exist.
 *
 * Brands and classification values are the opposite and are typed freely, with
 * what already exists offered as suggestions. Which *kinds* of grouping exist
 * is a decision about the merchandise model; which values they hold is the
 * shop's own data, and `Sandals` entered for the first time is a new category
 * rather than a mistake.
 *
 * **The SKU is not on this form and never will be.** It is generated by the
 * catalog, printed on the shelf label, and the request schema refuses one.
 */
export function NewProductForm({
  metadata,
  onCreated,
  onCancel,
}: {
  /** The catalog's own vocabulary. Absent while it loads; the form still works. */
  metadata: CatalogMetadataResponse | undefined;
  onCreated: (product: Product) => void;
  onCancel: () => void;
}) {
  const t = useTranslator();
  const { reportSessionEnded } = useAuth();
  const queryClient = useQueryClient();

  const [values, setValues] = useState<NewProductFormValues>(emptyNewProduct);
  const [fieldErrors, setFieldErrors] = useState<NewProductFieldErrors>({});

  const nameRef = useRef<HTMLInputElement>(null);
  const outcomeRef = useRef<HTMLDivElement>(null);

  const submit = useMutation({
    mutationFn: createProduct,
    onSuccess: (product) => {
      onCreated(product);
      /**
       * Two reads are now out of date, and for different reasons. The product
       * list has a new product in it. The metadata may have a new brand or a
       * new classification value: both are created as a side effect of entering
       * merchandise, so a second product entered afterwards should offer what
       * the first one introduced.
       */
      void queryClient.invalidateQueries({ queryKey: catalogProductsQueryKey }).catch(() => {});
      void queryClient.invalidateQueries({ queryKey: catalogMetadataQueryKey }).catch(() => {});
    },
    onError: (error) => {
      if (error instanceof ApiError && error.status === 401) reportSessionEnded();
    },
  });

  useEffect(() => {
    if (submit.isError) outcomeRef.current?.focus();
  }, [submit.isError]);

  function update(next: Partial<NewProductFormValues>): void {
    setValues((current) => ({ ...current, ...next }));
  }

  function updateVariant(index: number, next: NewProductFormValues['variants'][number]): void {
    setValues((current) => ({
      ...current,
      variants: current.variants.map((variant, position) => (position === index ? next : variant)),
    }));
  }

  /**
   * Closes the form and reloads the list.
   *
   * The answer to "did that work?" is on the list, not in this form, and going
   * to look is the only safe move after an answer nobody received.
   */
  function checkTheList(): void {
    void queryClient.invalidateQueries({ queryKey: catalogProductsQueryKey }).catch(() => {});
    onCancel();
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    if (submit.isPending) return;

    const errors = validateNewProductForm(values);
    if (Object.keys(errors).length > 0) {
      setFieldErrors(errors);
      if (errors.name) nameRef.current?.focus();
      return;
    }

    setFieldErrors({});
    submit.mutate(toCreateProductRequest(values));
  }

  const dimensions = metadata?.classificationDimensions ?? [];

  return (
    <form className={`${PANEL} flex flex-col gap-6`} onSubmit={handleSubmit} noValidate>
      <div>
        <h2 className="text-xl font-semibold text-ink">{t('catalog.newProductTitle')}</h2>
        <p className="mt-1 text-[15px] text-ink-soft">{t('catalog.newProductDescription')}</p>
      </div>

      {/* Product ------------------------------------------------------- */}
      <fieldset className="flex flex-col gap-4">
        {/* A `legend` rather than a heading: these are the two groups of one
            form, and an `h3` here would put a heading level under a heading
            that names the same form. */}
        <legend className="text-lg font-semibold text-ink">{t('catalog.sectionProduct')}</legend>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-1 sm:col-span-2">
            <label htmlFor="product-name" className={FIELD_LABEL}>
              {t('catalog.productName')}
            </label>
            <input
              ref={nameRef}
              id="product-name"
              name="name"
              className={TEXT_INPUT}
              value={values.name}
              /* No `maxLength`: a browser that silently stops accepting
                 characters tells somebody nothing, and the bound is checked
                 against the shared constant on submit with a sentence that
                 says what is wrong. */
              aria-invalid={fieldErrors.name !== undefined}
              onChange={(event) => update({ name: event.target.value })}
            />
            {fieldErrors.name && <p className={FIELD_ERROR}>{t(fieldErrors.name)}</p>}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="product-brand" className={FIELD_LABEL}>
              {t('catalog.brand')}
            </label>
            {/* Typed, with what exists offered. A brand is data about one
                product and costs nothing to add; the server matches an existing
                one case-insensitively rather than creating a second spelling. */}
            <input
              id="product-brand"
              name="brand"
              className={TEXT_INPUT}
              list="brand-suggestions"
              value={values.brand}
              onChange={(event) => update({ brand: event.target.value })}
            />
            <datalist id="brand-suggestions">
              {(metadata?.brands ?? []).map((brand) => (
                <option key={brand.id} value={brand.name} />
              ))}
            </datalist>
            <p className={FIELD_HINT}>{t('catalog.brandHint')}</p>
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="product-description" className={FIELD_LABEL}>
              {t('catalog.productDescription')}
            </label>
            <input
              id="product-description"
              name="description"
              className={TEXT_INPUT}
              value={values.description}
              aria-invalid={fieldErrors.description !== undefined}
              onChange={(event) => update({ description: event.target.value })}
            />
            {fieldErrors.description && <p className={FIELD_ERROR}>{t(fieldErrors.description)}</p>}
          </div>

          {/* The dimensions the server defines, whatever they are. Nothing here
              knows that this shop sells footwear: a fourth dimension added by a
              migration appears without a line of this file changing. */}
          {dimensions.map((dimension) => (
            <div key={dimension.key} className="flex flex-col gap-1">
              <label htmlFor={`classification-${dimension.key}`} className={FIELD_LABEL}>
                {dimension.name}
              </label>
              <input
                id={`classification-${dimension.key}`}
                className={TEXT_INPUT}
                list={`classification-${dimension.key}-values`}
                value={values.classifications[dimension.key] ?? ''}
                onChange={(event) =>
                  update({
                    classifications: {
                      ...values.classifications,
                      [dimension.key]: event.target.value,
                    },
                  })
                }
              />
              <datalist id={`classification-${dimension.key}-values`}>
                {dimension.values.map((value) => (
                  <option key={value.id} value={value.value} />
                ))}
              </datalist>
            </div>
          ))}
        </div>
      </fieldset>

      {/* Variants ------------------------------------------------------ */}
      <fieldset className="flex flex-col gap-4">
        <legend className="text-lg font-semibold text-ink">{t('catalog.sectionVariants')}</legend>
        <p className="text-sm text-ink-soft">{t('catalog.variantsHint')}</p>

        {values.variants.map((variant, index) => (
          <VariantFields
            key={index}
            index={index}
            variant={variant}
            definitions={metadata?.variantAttributeDefinitions ?? []}
            errors={fieldErrors}
            removable={values.variants.length > 1}
            onChange={(next) => updateVariant(index, next)}
            onRemove={() =>
              update({ variants: values.variants.filter((_, position) => position !== index) })
            }
          />
        ))}

        <div>
          <button
            type="button"
            className={SECONDARY_BUTTON}
            onClick={() => update({ variants: [...values.variants, emptyVariant()] })}
          >
            {t('catalog.addVariant')}
          </button>
        </div>
      </fieldset>

      {/* The one thing worth saying about identity, said once, where somebody
          would otherwise look for a field to type it in. */}
      <p className={FIELD_HINT}>{t('catalog.skuGenerated')}</p>

      {submit.isError && (
        <div ref={outcomeRef} tabIndex={-1} className={OUTCOME_FOCUS}>
          {isUncertain(submit.error) ? (
            /* A product is not a ledger command: this route carries no
               operation id and no name is unique, so a blind retry after an
               answer that never arrived would be a second product. The honest
               thing to offer is the list, which is where the answer is. */
            <div
              role="alert"
              className="flex flex-col items-start gap-3 rounded-md border border-warning bg-warning-soft px-3.5 py-3 text-[15px] text-warning-ink"
            >
              <p className="text-pretty">{t('catalog.uncertain')}</p>
              <button type="button" className={SECONDARY_BUTTON} onClick={checkTheList}>
                {t('catalog.checkList')}
              </button>
            </div>
          ) : isVariantConflict(submit.error) ? (
            <p
              role="alert"
              className="rounded-md border border-danger bg-danger-soft px-3.5 py-3 text-[15px] font-semibold text-danger-ink"
            >
              {t('catalog.variantExists')}
            </p>
          ) : (
            <ErrorNotice error={submit.error} />
          )}
        </div>
      )}

      <div className="flex flex-wrap gap-2">
        {/* Disabled while its own request is open, which no other form in this
            application does. Receiving may be pressed again because the server
            recognises the repeat; this route has no operation id and no
            uniqueness on a product name, so a second press would be a second
            product and nothing on the server would catch it. */}
        <button
          type="submit"
          disabled={submit.isPending}
          className={submit.isPending ? PRIMARY_BUTTON_BUSY : PRIMARY_BUTTON}
        >
          {submit.isPending ? t('catalog.submitting') : t('catalog.create')}
        </button>
        <button type="button" className={SECONDARY_BUTTON} onClick={onCancel}>
          {t('action.cancel')}
        </button>
      </div>
    </form>
  );
}

/**
 * An answer that never arrived, or one the server could not give: a dropped
 * connection, or a 5xx. Either way the product may or may not exist, and only
 * the list can say.
 */
function isUncertain(error: unknown): boolean {
  if (error instanceof NetworkError) return true;
  return error instanceof ApiError && error.status >= 500;
}

/**
 * The one refusal this form says something specific about: a variant with these
 * attributes already exists, which the person fixes by changing them.
 * Everything else goes to the shared `ErrorNotice`, which already handles
 * `401`, `403`, and the unexpected.
 */
function isVariantConflict(error: unknown): boolean {
  return error instanceof ApiError && error.status === 409 && error.code === 'CONFLICT';
}
