import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import {
  ATTRIBUTE_NAME_MAX_LENGTH,
  ATTRIBUTE_VALUE_MAX_LENGTH,
  PRODUCT_DESCRIPTION_MAX_LENGTH,
  PRODUCT_NAME_MAX_LENGTH,
  type Product,
} from '@ekon/shared';
import { useAuth } from '../auth/useAuth.js';
import { ErrorNotice } from '../components/ErrorNotice.js';
import {
  FIELD_ERROR,
  FIELD_HINT,
  FIELD_LABEL,
  OUTCOME_FOCUS,
  PANEL,
  PRIMARY_BUTTON,
  PRIMARY_BUTTON_BUSY,
  SECONDARY_BUTTON,
  TEXT_INPUT,
} from '../components/styles.js';
import { useTranslator } from '../i18n/index.js';
import { ApiError, NetworkError } from '../lib/api.js';
import {
  emptyNewProduct,
  toCreateProductRequest,
  validateNewProductForm,
  type NewProductFieldErrors,
  type NewProductFormValues,
} from '../lib/catalog.js';
import { createProduct } from '../lib/catalogApi.js';
import { catalogProductsQueryKey } from '../lib/catalogQueries.js';
import { formatVariantAttributes } from '../lib/variants.js';

/**
 * Creating a product, so there is something the shop can take stock of.
 *
 * The first workflow of the operating loop, and until it existed a fresh
 * installation had nothing to receive: an employee could sign in, open
 * receiving, and find an empty list, because the only way to put a product in
 * the catalog was an API call typed by hand.
 *
 * It is one form on purpose. There is no editing, no deactivation, no price, no
 * cost, no supplier, and no category — each of those is a separate decision
 * about what the catalog *is*, and none of them is needed to receive a sack of
 * rice. What the business needed in order to open was the ability to put an
 * item in the catalog; that is the whole of what is here.
 *
 * **A product is not a ledger command.** Receiving may be pressed again after a
 * dropped connection because the operation id makes the server recognize the
 * repeat; there is no such contract on this route and no unique constraint on a
 * product name, so a blind second attempt would be a second product. Nothing
 * here retries automatically, and an answer that never arrived is said as
 * exactly that — with a way to go and look at the list rather than a button
 * that invites a duplicate.
 */

/**
 * Server-owned fields have no input, and could not be sent if they had one:
 * every request goes through the shared `.strict()` schema, which refuses an
 * `id`, a `variantSignature`, and above all a `sku` — the SKU is generated by
 * the catalog and is the shop's one printed identifier for a variant.
 */
export function NewProductForm({
  onCreated,
  onCancel,
}: {
  onCreated: (product: Product) => void;
  onCancel: () => void;
}) {
  const t = useTranslator();
  const { reportSessionEnded } = useAuth();
  const queryClient = useQueryClient();

  const [values, setValues] = useState<NewProductFormValues>(emptyNewProduct);
  const [fieldErrors, setFieldErrors] = useState<NewProductFieldErrors>({});

  const nameRef = useRef<HTMLInputElement>(null);
  const outcomeRef = useRef<HTMLDivElement>(null);

  const submit = useMutation({
    mutationFn: createProduct,
    onSuccess: (product) => {
      onCreated(product);

      /**
       * The catalog now says something out of date, and two screens read it:
       * this list, and the variant choices on receiving. Invalidating the one
       * key both of them use is what makes a product created here selectable
       * there without anybody reloading the page.
       *
       * Last, and deliberately after the screen has been told. The product is
       * already created — the server answered `201` — so nothing about tidying
       * a cache may turn it into an ambiguous "did that work?". Fire and
       * forget, with the rejection swallowed for the same reason: a refetch
       * that fails is the list's problem to render.
       */
      void queryClient.invalidateQueries({ queryKey: catalogProductsQueryKey }).catch(() => {});
    },
    onError: (error) => {
      // A mutation is a protected request like any other, and a 401 back from
      // one means what it means on a read: the session ended. Reads go through
      // `useProtectedQuery`; this is the same rule, said once here.
      if (error instanceof ApiError && error.status === 401) reportSessionEnded();
    },
  });

  // The failure is where the reader needs to be. It is announced by its
  // `role="alert"`; moving focus there as well means somebody on a keyboard
  // lands on the answer rather than on a form that appears to have done nothing.
  useEffect(() => {
    if (submit.isError) outcomeRef.current?.focus();
  }, [submit.isError]);

  function update(next: Partial<NewProductFormValues>): void {
    setValues((current) => ({ ...current, ...next }));
  }

  function updateAttribute(
    variantIndex: number,
    attributeIndex: number,
    next: Partial<{ name: string; value: string }>,
  ): void {
    setValues((current) => ({
      ...current,
      variants: current.variants.map((variant, index) =>
        index !== variantIndex
          ? variant
          : {
              attributes: variant.attributes.map((attribute, position) =>
                position === attributeIndex ? { ...attribute, ...next } : attribute,
              ),
            },
      ),
    }));
  }

  function addAttribute(variantIndex: number): void {
    setValues((current) => ({
      ...current,
      variants: current.variants.map((variant, index) =>
        index === variantIndex
          ? { attributes: [...variant.attributes, { name: '', value: '' }] }
          : variant,
      ),
    }));
  }

  function removeAttribute(variantIndex: number, attributeIndex: number): void {
    setValues((current) => ({
      ...current,
      variants: current.variants.map((variant, index) =>
        index === variantIndex
          ? { attributes: variant.attributes.filter((_, position) => position !== attributeIndex) }
          : variant,
      ),
    }));
    setFieldErrors({});
  }

  function addVariant(): void {
    setValues((current) => ({ ...current, variants: [...current.variants, { attributes: [] }] }));
  }

  function removeVariant(variantIndex: number): void {
    setValues((current) => ({
      ...current,
      variants: current.variants.filter((_, index) => index !== variantIndex),
    }));
    // Positions shift, so errors keyed by position no longer describe the form.
    setFieldErrors({});
  }

  /**
   * The list is where somebody finds out whether an answer that never arrived
   * created a product. Re-reading it is the safe move; sending the request
   * again is the one that makes two.
   */
  function checkTheList(): void {
    void queryClient.invalidateQueries({ queryKey: catalogProductsQueryKey }).catch(() => {});
    onCancel();
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    // A second press while the first request is open would create the product
    // twice — this route has no operation id and no name uniqueness to lean on.
    if (submit.isPending) return;

    const errors = validateNewProductForm(values);
    if (Object.keys(errors).length > 0) {
      setFieldErrors(errors);
      submit.reset();
      if (errors.name) nameRef.current?.focus();
      return;
    }

    /**
     * Built and then parsed by the *shared* schema inside `createProduct` — the
     * same one the route parses, so the browser and the server cannot disagree
     * about what a product is, and nothing the server owns can reach the wire.
     */
    setFieldErrors({});
    submit.mutate(toCreateProductRequest(values));
  }

  const attributeError = (variantIndex: number, attributeIndex: number) =>
    fieldErrors.attributes?.[`${variantIndex}.${attributeIndex}`];

  return (
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,640px)_1fr]">
      <form
        onSubmit={handleSubmit}
        noValidate
        aria-label={t('catalog.newProductTitle')}
        className={`${PANEL} flex flex-col gap-4.5`}
      >
        <div>
          <h2 className="text-lg font-semibold text-ink">{t('catalog.newProductTitle')}</h2>
          <p className="mt-1 text-[15px] text-ink-soft">{t('catalog.newProductDescription')}</p>
        </div>

        {submit.isError && (
          <div ref={outcomeRef} tabIndex={-1} className={OUTCOME_FOCUS}>
            {isUncertain(submit.error) ? (
              <div
                role="alert"
                className="flex flex-col items-start gap-3 rounded-md border border-warning bg-warning-soft px-3.5 py-3 text-[15px] text-warning-ink"
              >
                <p className="text-pretty">{t('catalog.uncertain')}</p>
                <button type="button" className={SECONDARY_BUTTON} onClick={checkTheList}>
                  {t('catalog.checkList')}
                </button>
              </div>
            ) : isVariantConflict(submit.error) ? (
              <p
                role="alert"
                className="rounded-md border border-danger bg-danger-soft px-3.5 py-3 text-[15px] font-semibold text-danger-ink"
              >
                {t('catalog.variantExists')}
              </p>
            ) : (
              <ErrorNotice error={submit.error} />
            )}
          </div>
        )}

        <div className="flex flex-col gap-1.5">
          <label htmlFor="new-product-name" className={FIELD_LABEL}>
            {t('catalog.productName')}
          </label>
          <input
            id="new-product-name"
            ref={nameRef}
            name="name"
            type="text"
            autoComplete="off"
            maxLength={PRODUCT_NAME_MAX_LENGTH}
            required
            className={TEXT_INPUT}
            value={values.name}
            onChange={(event) => update({ name: event.target.value })}
            aria-invalid={fieldErrors.name ? true : undefined}
            aria-describedby={fieldErrors.name ? 'new-product-name-error' : 'new-product-name-hint'}
          />
          {fieldErrors.name ? (
            <p id="new-product-name-error" className={FIELD_ERROR}>
              {t(fieldErrors.name, { max: PRODUCT_NAME_MAX_LENGTH })}
            </p>
          ) : (
            <p id="new-product-name-hint" className={FIELD_HINT}>
              {t('catalog.productNameHint')}
            </p>
          )}
        </div>

        <div className="flex flex-col gap-1.5">
          <label htmlFor="new-product-description" className={FIELD_LABEL}>
            {t('catalog.productDescription')}
          </label>
          <textarea
            id="new-product-description"
            name="description"
            rows={2}
            maxLength={PRODUCT_DESCRIPTION_MAX_LENGTH}
            className={TEXT_INPUT}
            value={values.description}
            onChange={(event) => update({ description: event.target.value })}
            aria-invalid={fieldErrors.description ? true : undefined}
            aria-describedby={fieldErrors.description ? 'new-product-description-error' : undefined}
          />
          {fieldErrors.description && (
            <p id="new-product-description-error" className={FIELD_ERROR}>
              {t(fieldErrors.description, { max: PRODUCT_DESCRIPTION_MAX_LENGTH })}
            </p>
          )}
        </div>

        <fieldset className="flex flex-col gap-3.5 border-t border-rule pt-4.5">
          {/* A direct child of the fieldset, which is the only place a legend
              names the group it belongs to. The action sits on the line under
              it rather than beside it, because moving the legend into a flex
              row would cost that association for a few pixels of alignment. */}
          <legend className="text-base font-semibold text-ink">
            {t('catalog.variantsLegend')}
          </legend>

          <p className={FIELD_HINT}>{t('catalog.variantsHint')}</p>

          {values.variants.map((variant, variantIndex) => (
            <div
              key={variantIndex}
              className="flex flex-col gap-3 rounded-md border border-line bg-canvas p-4"
            >
              <div className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1">
                <h3 className="text-[15px] font-semibold text-ink">
                  {t('catalog.variantNumber', { number: variantIndex + 1 })}
                </h3>
                {values.variants.length > 1 && (
                  <button
                    type="button"
                    className={QUIET_BUTTON}
                    aria-label={t('catalog.removeVariant', { number: variantIndex + 1 })}
                    onClick={() => removeVariant(variantIndex)}
                  >
                    {t('catalog.remove')}
                  </button>
                )}
              </div>

              {fieldErrors.variants?.[String(variantIndex)] && (
                <p role="alert" className={FIELD_ERROR}>
                  {t('catalog.duplicateVariant')}
                </p>
              )}

              {variant.attributes.map((attribute, attributeIndex) => {
                const error = attributeError(variantIndex, attributeIndex);
                const base = `new-product-v${variantIndex}-a${attributeIndex}`;
                return (
                  <div key={attributeIndex} className="flex flex-col gap-1.5">
                    <div className="flex flex-wrap items-end gap-3">
                      <div className="flex min-w-38 flex-1 flex-col gap-1.5">
                        <label htmlFor={`${base}-name`} className="text-sm font-semibold text-ink">
                          {t('catalog.attributeName')}
                        </label>
                        <input
                          id={`${base}-name`}
                          type="text"
                          autoComplete="off"
                          maxLength={ATTRIBUTE_NAME_MAX_LENGTH}
                          className={TEXT_INPUT}
                          value={attribute.name}
                          onChange={(event) =>
                            updateAttribute(variantIndex, attributeIndex, {
                              name: event.target.value,
                            })
                          }
                          aria-invalid={error ? true : undefined}
                          aria-describedby={error ? `${base}-error` : undefined}
                        />
                      </div>
                      <div className="flex min-w-38 flex-1 flex-col gap-1.5">
                        <label htmlFor={`${base}-value`} className="text-sm font-semibold text-ink">
                          {t('catalog.attributeValue')}
                        </label>
                        <input
                          id={`${base}-value`}
                          type="text"
                          autoComplete="off"
                          maxLength={ATTRIBUTE_VALUE_MAX_LENGTH}
                          className={TEXT_INPUT}
                          value={attribute.value}
                          onChange={(event) =>
                            updateAttribute(variantIndex, attributeIndex, {
                              value: event.target.value,
                            })
                          }
                          aria-invalid={error ? true : undefined}
                          aria-describedby={error ? `${base}-error` : undefined}
                        />
                      </div>
                      {/* A 48px control, so it is a real target on a tablet.
                          The cross is decoration; the label is the sentence. */}
                      <button
                        type="button"
                        className={`${SECONDARY_BUTTON} size-12 shrink-0 px-0 text-lg`}
                        aria-label={t('catalog.removeAttribute')}
                        onClick={() => removeAttribute(variantIndex, attributeIndex)}
                      >
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    {error && (
                      <p id={`${base}-error`} className={FIELD_ERROR}>
                        {t(error)}
                      </p>
                    )}
                  </div>
                );
              })}

              <div>
                <button
                  type="button"
                  className={QUIET_BUTTON}
                  onClick={() => addAttribute(variantIndex)}
                >
                  {t('catalog.addAttribute')}
                </button>
              </div>
            </div>
          ))}

          {/* After the variants rather than beside the legend: "add another"
              belongs at the end of the list it adds to, and it reads the same
              way as the add-an-attribute action inside each card. */}
          <div>
            <button type="button" className={QUIET_BUTTON} onClick={addVariant}>
              {t('catalog.addVariant')}
            </button>
          </div>
        </fieldset>

        <div className="flex flex-wrap gap-2.5 border-t border-rule pt-4.5">
          <button
            type="submit"
            className={submit.isPending ? PRIMARY_BUTTON_BUSY : PRIMARY_BUTTON}
            disabled={submit.isPending}
            aria-busy={submit.isPending}
          >
            {submit.isPending && (
              <span
                aria-hidden="true"
                className="mr-2.5 inline-block size-3.5 animate-spin rounded-full border-2 border-white/45 border-t-white motion-reduce:animate-none"
              />
            )}
            {submit.isPending ? t('catalog.submitting') : t('catalog.submit')}
          </button>
          <button
            type="button"
            className={SECONDARY_BUTTON}
            onClick={onCancel}
            disabled={submit.isPending}
          >
            {t('action.cancel')}
          </button>
        </div>
      </form>

      <CreationSummary values={values} />
    </div>
  );
}

/**
 * A quiet action inside the form: adding a variant, adding an attribute,
 * removing one. Accent text on nothing, because a form with five bordered
 * buttons in it reads as five decisions of equal weight, and only one of them
 * is "create the product".
 */
const QUIET_BUTTON =
  'inline-flex min-h-touch items-center rounded-md px-2.5 text-[15px] font-semibold text-accent ' +
  'hover:bg-accent-soft focus-visible:outline-2 focus-visible:outline-offset-2 ' +
  'focus-visible:outline-accent-focus';

/**
 * What this form will create, restated beside it.
 *
 * Only what has been typed — no field the form does not have, and no SKU. The
 * SKU box is here precisely to say that the SKU is not a decision anybody makes
 * on this screen: the catalog generates it, and somebody hunting for the field
 * to type one into should find this sentence instead.
 *
 * The last line is the one that matters after a dropped connection. This route
 * carries no operation id and no name is unique, so a second attempt is a
 * second product — the safe move is to go and look at the list.
 */
function CreationSummary({ values }: { values: NewProductFormValues }) {
  const t = useTranslator();
  const name = values.name.trim();

  return (
    <aside className={`${PANEL} flex flex-col gap-3`} aria-label={t('catalog.preview')}>
      <p className="text-xs font-bold tracking-[0.1em] text-accent uppercase">
        {t('catalog.preview')}
      </p>

      <div>
        {name === '' ? (
          <p className="text-[15px] text-ink-soft">{t('catalog.previewNoName')}</p>
        ) : (
          <p className="text-lg font-semibold text-ink">{name}</p>
        )}

        <ul className="mt-0.5 flex flex-col">
          {values.variants.map((variant, index) => {
            const attributes = formatVariantAttributes(
              variant.attributes.filter(
                (attribute) => attribute.name.trim() !== '' && attribute.value.trim() !== '',
              ),
            );
            return (
              <li
                key={index}
                className={attributes === '' ? 'text-[15px] text-ink-soft' : 'text-[15px] text-ink'}
              >
                {attributes === '' ? t('catalog.noAttributes') : attributes}
              </li>
            );
          })}
        </ul>
      </div>

      <div className="flex flex-col gap-1 rounded-md border border-line bg-canvas p-3">
        <span className="text-xs font-bold tracking-[0.08em] text-ink-muted uppercase">
          {t('catalog.sku')}
        </span>
        <span className="text-[15px] text-ink-soft">{t('catalog.skuServerGenerated')}</span>
      </div>

      <p className="text-sm text-pretty text-ink-soft">{t('catalog.noOperationId')}</p>
    </aside>
  );
}

/**
 * An answer that never arrived, or one the server could not give.
 *
 * The distinction that matters is not "did it fail" but "do we know". A `400`
 * or a `403` is the server telling us something true and nothing was written; a
 * dropped connection or a `500` leaves a product that may or may not exist, and
 * the only safe next step is to look at the list rather than send it again.
 */
function isUncertain(error: unknown): boolean {
  if (error instanceof NetworkError) return true;
  return error instanceof ApiError && error.status >= 500;
}

/**
 * The one refusal this form says something specific about: a variant with these
 * attributes already exists, which the person fixes by changing them.
 * Everything else goes to the shared `ErrorNotice`, which already handles
 * `401`, `403`, and the unexpected.
 */
function isVariantConflict(error: unknown): boolean {
  return error instanceof ApiError && error.status === 409 && error.code === 'CONFLICT';
}
