import { z } from 'zod';

/**
 * The closed set of ways stock can change. Every one of these is an append-only
 * row in `inventory_movements`; none of them ever updates a quantity in place.
 *
 * Defined here in Sprint 0 so the vocabulary is fixed before the inventory
 * module is built. The tables themselves arrive in the ledger PR.
 */
export const MOVEMENT_TYPES = [
  'RECEIPT',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT',
  'COUNT_RECONCILIATION',
  'REVERSAL',
] as const;

export const movementTypeSchema = z.enum(MOVEMENT_TYPES);
export type MovementType = z.infer<typeof movementTypeSchema>;

/** Movement types that require a non-null `reason_code`. */
export const REASON_REQUIRED_MOVEMENT_TYPES: readonly MovementType[] = [
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT',
];

/**
 * Quantities are always integers in whole base units. Never floats — a
 * floating-point quantity in an inventory ledger is an unfixable data-integrity
 * defect once history exists.
 */
export const quantitySchema = z.number().int().nonnegative();
export const quantityDeltaSchema = z
  .number()
  .int()
  .refine((n) => n !== 0, {
    message: 'quantity_delta must not be zero',
  });

/** UUIDv7, generated at the point of capture. */
export const idSchema = z.string().uuid();

/**
 * Every state-changing request carries an operation id generated by the client
 * *before* the first attempt and reused on every retry, including after a page
 * reload. Generating a fresh id per retry defeats duplicate protection entirely.
 */
export const operationIdSchema = idSchema;
