import { z } from 'zod';

/**
 * The closed set of ways stock can change. Every one of these is an append-only
 * row in `inventory_movements`; none of them ever updates a quantity in place.
 *
 * Defined here in Sprint 0 so the vocabulary is fixed before the inventory
 * module is built. The tables themselves arrive in the ledger PR.
 */
export const MOVEMENT_TYPES = [
  'RECEIPT',
  'ISSUE',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT',
  'COUNT_RECONCILIATION',
  'REVERSAL',
] as const;

export const movementTypeSchema = z.enum(MOVEMENT_TYPES);
export type MovementType = z.infer<typeof movementTypeSchema>;

/**
 * Movement types that require a non-null `reason_code`.
 *
 * Two different questions get the same answer here, and it is worth saying why.
 *
 * An **adjustment** says the recorded balance was wrong. The number changed
 * without the stock moving, so the only account of what happened is the reason
 * somebody wrote down; without it the ledger records an unexplained correction.
 *
 * An **issue** says stock left through ordinary operations. The stock really
 * moved, but "it left" is not yet a business fact anybody can act on — sold,
 * broken, or taken for the shop's own use are three different things, and a
 * shop that cannot tell them apart cannot tell trade from loss. So the reason
 * is the fact, and the type without it is half a record.
 *
 * `RECEIPT` carries its reason in its type: stock arrived. A count carries it
 * in the count, and a reversal in the movement it reverses.
 */
export const REASON_REQUIRED_MOVEMENT_TYPES: readonly MovementType[] = [
  'ISSUE',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT',
];

/**
 * Quantities are always integers in whole base units. Never floats — a
 * floating-point quantity in an inventory ledger is an unfixable data-integrity
 * defect once history exists.
 */
export const quantitySchema = z.number().int().nonnegative();
export const quantityDeltaSchema = z
  .number()
  .int()
  .refine((n) => n !== 0, {
    message: 'quantity_delta must not be zero',
  });

/**
 * The largest quantity any single movement may carry.
 *
 * `quantity_delta`, `quantity_before`, and `quantity_after` are `integer`
 * columns, so this is the database's own ceiling rather than a business policy.
 * Stated here so a request that could never be stored is refused as a `400`
 * instead of failing inside a transaction as a `500`.
 */
export const MAX_MOVEMENT_QUANTITY = 2_147_483_647;

/**
 * The longest note any movement may carry.
 *
 * `inventory_movements.note` is bounded at 500 characters by a CHECK (0005), so
 * this is the database's own ceiling rather than a business policy. Stated here
 * so a note that could never be stored is refused as a `400` instead of failing
 * inside a transaction as a `500`.
 */
export const MAX_MOVEMENT_NOTE_LENGTH = 500;

/**
 * Free text somebody types at the counter, for the workflows that offer one.
 *
 * Trimmed and bounded, and **never blank**: a note consisting of spaces is an
 * empty note wearing a value's clothes, and storing one would make
 * "somebody explained this" indistinguishable from "nobody did". A workflow
 * that has no note field does not invent one — receiving and removal each
 * deliberately carry no note at all.
 *
 * It is not a reason. A reason is a code from a closed vocabulary that a report
 * can count; a note is the sentence a person wrote beside it, which nothing
 * counts and nothing parses.
 */
export const noteSchema = z
  .string()
  .trim()
  .min(1, 'A note must not be blank')
  .max(MAX_MOVEMENT_NOTE_LENGTH);

/** UUIDv7, generated at the point of capture. */
export const idSchema = z.string().uuid();

/**
 * Every state-changing request carries an operation id generated by the client
 * *before* the first attempt and reused on every retry, including after a page
 * reload. Generating a fresh id per retry defeats duplicate protection entirely.
 */
export const operationIdSchema = idSchema;

/**
 * When the stock physically moved — **business time**, and the caller's to
 * state. A delivery counted this morning and entered this afternoon occurred
 * this morning, so a value earlier than the server's own `recorded_at` is
 * ordinary rather than an error. It is never the time the server recorded the
 * movement: that is the ledger's, and no request supplies it.
 *
 * An offset is accepted as well as `Z`, because the phone or laptop stating the
 * business time is in Haiti and its clock is local. The server normalizes to
 * UTC once, so `10:00:00-05:00` and `15:00:00Z` are the same instant to both
 * the ledger and the request hash.
 *
 * A future timestamp is deliberately not refused here. Clocks on shop hardware
 * drift, and rejecting a delivery because a laptop is four minutes fast would
 * block real work to enforce nothing the ledger depends on.
 */
export const occurredAtSchema = z
  .string()
  .datetime({ offset: true, message: 'occurredAt must be an ISO 8601 timestamp' })
  .refine(isRealCalendarDate, 'occurredAt must be a real calendar date');

/**
 * What a workflow that posted one movement tells its caller.
 *
 * Three fields, and the same three whatever the command was: which command this
 * answers, the movement it produced, and what the shelf holds now. The ledger's
 * internals — the predecessor movement, the quantity before, the request hash,
 * the recorded time, the operation row's state — are how the server keeps its
 * own promises and are of no use to a screen that has just booked in a delivery
 * or recorded a sale.
 *
 * Defined once because receiving and removal genuinely answer the same shape,
 * and two hand-written copies of one contract are two things to keep in step.
 * It is deliberately *not* generic over the workflow: nothing in it names the
 * movement type, the direction, or the reason, because the caller already knows
 * what it asked for. What it does not know, and what only the server can say,
 * is `quantityAfter`.
 *
 * A retry of the same command returns this same body, with the same
 * `movementId`: replaying is answered, not re-posted.
 */
export const movementResultSchema = z
  .object({
    /** Echoed back so a client can match a response to the command it retried. */
    operationId: idSchema,
    /** The movement this command produced. Server-generated, and permanent. */
    movementId: idSchema,
    /** Quantity on hand for that (variant, location) after the movement. */
    quantityAfter: quantitySchema,
  })
  .strict();

export type MovementResult = z.infer<typeof movementResultSchema>;

/**
 * True when the date part of an ISO timestamp names a day that exists.
 *
 * The format check above accepts `2026-02-31`, and `new Date()` would silently
 * roll it forward to 3 March rather than refusing it — so a typo would be
 * stored as a real, wrong business date. This compares the parsed calendar
 * fields against what was written.
 */
function isRealCalendarDate(value: string): boolean {
  const year = Number(value.slice(0, 4));
  const month = Number(value.slice(5, 7));
  const day = Number(value.slice(8, 10));
  const asUtc = new Date(Date.UTC(year, month - 1, day));
  return (
    asUtc.getUTCFullYear() === year &&
    asUtc.getUTCMonth() === month - 1 &&
    asUtc.getUTCDate() === day
  );
}
